# Generated by Django 3.2.6 on 2022-01-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_added',
            field=models.DateTimeField(verbose_name='Date Added'),
        ),
    ]
